'use strict'

const fs = require('fs')
const path = require('path')
const { spawnSync } = require('child_process')

const WORKFLOW_ORDER = [
  'gate', 'test', 'commit', 'push', 'pr', 'branch', 'launch', 'lint',
  'security', 'docs', 'issue', 'architect', 'cloud-security',
  'enterprise-design', 'db', 'fix', 'spec', 'grill', 'techdebt',
  'context', 'query', 'orchestrate', 'update-claude',
]

function copyWorkflowsToClaudeCommands(workflowsDir, commandsDir) {
  fs.mkdirSync(commandsDir, { recursive: true })
  for (const file of fs.readdirSync(workflowsDir).filter(f => f.endsWith('.md'))) {
    const content = fs.readFileSync(path.join(workflowsDir, file), 'utf8')
    fs.writeFileSync(path.join(commandsDir, file), content + '\n$ARGUMENTS\n')
  }
  const dbEnginesDir = path.join(workflowsDir, 'db-engines')
  if (fs.existsSync(dbEnginesDir)) {
    const dstDbDir = path.join(commandsDir, 'db-engines')
    fs.mkdirSync(dstDbDir, { recursive: true })
    for (const file of fs.readdirSync(dbEnginesDir).filter(f => f.endsWith('.md'))) {
      fs.copyFileSync(path.join(dbEnginesDir, file), path.join(dstDbDir, file))
    }
  }
}

function scaffoldClaudeMd(projectPath) {
  const existing = [
    'CLAUDE.md', 'AGENTS.md', '.cursorrules', '.windsurfrules', 'GEMINI.md',
    path.join('.github', 'copilot-instructions.md'),
  ]
  if (existing.some(f => fs.existsSync(path.join(projectPath, f)))) return

  const projectName = path.basename(path.resolve(projectPath))
  fs.writeFileSync(path.join(projectPath, 'CLAUDE.md'), `# ${projectName} — Project Instructions

<!-- Generated by 100x-dev. Fill in the sections below so workflows like /db, /gate, /launch have project context. -->

## Project

<!-- Describe what this project does in 2-3 sentences. Used by /architect and /enterprise-design. -->
description: TODO

## Database

<!-- Used by /db and /query. Remove if not applicable. -->
# engine: postgres
# connection: default
# connections:
#   default:
#     host: localhost
#     port: 5432
#     name: mydb
#     user: myuser
#     auth: env:DB_PASSWORD

## Cloud (GCP)

<!-- Used by /gate, /cloud-security, /launch. Remove if not on GCP. -->
# gcp_project: my-gcp-project
# cloud_run_service: my-service
# region: us-central1

## Production

<!-- Used by /launch and /push for health checks and smoke tests. -->
# production_url: https://example.com
# health_url: https://example.com/health

## Security Exceptions

# security_exceptions:
#   - CVE-2023-XXXX: false positive in test dependency

## Rules

<!-- Add project-specific rules for Claude here. /update-claude appends to this section. -->
`)
  console.log(`  → Scaffolded CLAUDE.md in ${projectPath} ✓`)
}

// Reconcile enabledPlugins with plugins.json: ADD newly-declared plugins and
// REMOVE ones 100x-dev previously installed but has since dropped — without
// touching plugins the user enabled themselves. The "managed" set is tracked in
// a sidecar beside settings.json (mirrors adapters/lib/sync_plugins.py). On the
// first run (no state) the managed set is seeded from declared ∧ enabled, so
// nothing is removed until a later run observes an actual drop.
function mergePluginsJson(pluginsFile, settingsFile) {
  if (!fs.existsSync(settingsFile)) {
    fs.mkdirSync(path.dirname(settingsFile), { recursive: true })
    fs.writeFileSync(settingsFile, '{}')
  }
  const pluginsData = JSON.parse(fs.readFileSync(pluginsFile, 'utf8'))
  const settings = JSON.parse(fs.readFileSync(settingsFile, 'utf8'))
  const enabled = settings.enabledPlugins || {}
  const desired = pluginsData.plugins || []
  const desiredSet = new Set(desired)

  const stateFile = path.join(path.dirname(settingsFile), '.100x-dev-plugins.json')
  let state = {}
  try { state = JSON.parse(fs.readFileSync(stateFile, 'utf8')) } catch { state = {} }
  const firstRun = !('managed' in state)
  const managed = new Set(
    firstRun ? desired.filter(p => p in enabled) : (state.managed || []),
  )

  for (const p of desired) {
    if (!(p in enabled)) enabled[p] = true   // never flip an existing value
  }
  for (const p of managed) {
    if (!desiredSet.has(p)) delete enabled[p] // we installed it; it's gone now
  }

  settings.enabledPlugins = enabled
  settings.extraKnownMarketplaces = {
    ...settings.extraKnownMarketplaces,
    ...(pluginsData.extraKnownMarketplaces || {}),
  }
  fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2))
  fs.writeFileSync(stateFile, JSON.stringify({ managed: [...desiredSet].sort() }, null, 2))
}

function generateCombinedWorkflows(workflowsDir) {
  const lines = [
    '# 100x Dev Workflows',
    '# Generated by 100x-dev (https://github.com/rajitsaha/100x-dev)',
    '',
  ]
  for (const name of WORKFLOW_ORDER) {
    const file = path.join(workflowsDir, `${name}.md`)
    if (fs.existsSync(file)) {
      lines.push('---', '', fs.readFileSync(file, 'utf8').trimEnd(), '')
    }
  }
  return lines.join('\n')
}

function addTrackedProject(projectPath, trackedFile) {
  fs.mkdirSync(path.dirname(trackedFile), { recursive: true })
  const existing = fs.existsSync(trackedFile)
    ? fs.readFileSync(trackedFile, 'utf8').split('\n').filter(Boolean)
    : []
  if (!existing.includes(projectPath)) {
    fs.appendFileSync(trackedFile, projectPath + '\n')
  }
}

function writeAdapter(content, outputFile) {
  fs.mkdirSync(path.dirname(outputFile), { recursive: true })
  fs.writeFileSync(outputFile, content)
  console.log(`  → Generated ${outputFile} ✓`)
}

function installGlobalWindows(installDir) {
  const { claudeCommandsDir, claudeSettingsFile } = require('../platform')
  copyWorkflowsToClaudeCommands(path.join(installDir, 'workflows'), claudeCommandsDir)
  mergePluginsJson(path.join(installDir, 'plugins', 'plugins.json'), claudeSettingsFile)
  console.log('✓ Workflows installed to ~/.claude/commands/')
  console.log('✓ Plugins merged into ~/.claude/settings.json')
  console.log('\nNext: cd into a project and run  100x-dev init  to set it up.')
}

function initProjectWindows(installDir, projectPath) {
  const { trackedProjectsFile } = require('../platform')
  const workflowsDir = path.join(installDir, 'workflows')
  const absProject = path.resolve(projectPath)
  const readline = require('readline')
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

  console.log('\n100x Dev — Project Setup')
  console.log(`  Project: ${absProject}\n`)

  const tools = [
    { label: 'Claude Code (CLAUDE.md scaffold)', key: 'claude' },
    { label: 'Cursor (.cursorrules)', key: 'cursor' },
    { label: 'Codex (AGENTS.md)', key: 'codex' },
    { label: 'Windsurf (.windsurfrules)', key: 'windsurf' },
    { label: 'Copilot CLI (.github/copilot-instructions.md)', key: 'copilot' },
    { label: 'Gemini CLI (GEMINI.md)', key: 'gemini' },
    { label: 'Antigravity (ANTIGRAVITY.md)', key: 'antigravity' },
  ]
  const selected = {}

  function promptNext(idx) {
    if (idx >= tools.length) {
      rl.close()
      applyAdapters()
      return
    }
    rl.question(`  Set up ${tools[idx].label}? [y/N] `, ans => {
      selected[tools[idx].key] = /^y$/i.test(ans.trim())
      promptNext(idx + 1)
    })
  }

  function applyAdapters() {
    const combined = generateCombinedWorkflows(workflowsDir)
    if (selected.claude)      scaffoldClaudeMd(absProject)
    if (selected.cursor)      writeAdapter(combined, path.join(absProject, '.cursorrules'))
    if (selected.codex)       writeAdapter(combined, path.join(absProject, 'AGENTS.md'))
    if (selected.windsurf)    writeAdapter(combined, path.join(absProject, '.windsurfrules'))
    if (selected.copilot)     writeAdapter(combined, path.join(absProject, '.github', 'copilot-instructions.md'))
    if (selected.gemini)      writeAdapter(combined, path.join(absProject, 'GEMINI.md'))
    if (selected.antigravity) writeAdapter(combined, path.join(absProject, 'ANTIGRAVITY.md'))
    addTrackedProject(absProject, trackedProjectsFile)
    console.log('\n✓ Project set up!')
  }

  promptNext(0)
}

function updateWindows(installDir, checkOnly) {
  const fetchResult = spawnSync('git', ['-C', installDir, 'fetch', 'origin', 'main', '--quiet'], { stdio: 'inherit' })
  if (fetchResult.status !== 0) { console.error('git fetch failed'); process.exit(1) }

  const local  = spawnSync('git', ['-C', installDir, 'rev-parse', 'HEAD']).stdout.toString().trim()
  const remote = spawnSync('git', ['-C', installDir, 'rev-parse', 'origin/main']).stdout.toString().trim()

  if (local === remote) { console.log('✓ Already up to date.'); return }

  if (checkOnly) { console.log('Update available. Run: 100x-dev update'); return }

  const pullResult = spawnSync('git', ['-C', installDir, 'pull', '--rebase', 'origin', 'main', '--quiet'], { stdio: 'inherit' })
  if (pullResult.status !== 0) { console.error('git pull failed'); process.exit(1) }

  installGlobalWindows(installDir)
  console.log('✓ 100x-dev updated!')
}

module.exports = {
  copyWorkflowsToClaudeCommands,
  scaffoldClaudeMd,
  mergePluginsJson,
  generateCombinedWorkflows,
  addTrackedProject,
  installGlobalWindows,
  initProjectWindows,
  updateWindows,
}
