'use strict'

const fs = require('fs')
const path = require('path')
const { spawnSync } = require('child_process')

// ── v2 module emit (pure-JS port of adapters/lib/modules.py emit-claude-code) ──
// Windows has no bash, so the Node path can't call install.sh/update.sh. This
// mirrors the Python emitter: parse modules/<slug>/SKILL.md, write Claude Code
// skills + slash-command aliases, and prune anything we previously emitted that
// no longer exists — without touching the user's own skills/commands.

const GENERATED_MARKER = '.100xprism-generated'
const ALIAS_MARKER = '<!-- 100xprism generated alias — regenerate, do not edit -->'
const MANIFEST_NAME = '.100xprism-manifest.json'
// Modules removed/merged upstream — cleaned up even for installs that predate the
// manifest/marker. Safe to trim once installs have cycled through a v2 update.
const REMOVED_MODULES = new Set(['systems-architect', 'conversion-copy'])

const MODEL_TIER_HINT = {
  haiku: 'fast / low-cost (mechanical task)',
  sonnet: 'balanced (moderate reasoning)',
  opus: 'most capable (deep reasoning)',
}
const CATEGORY_ORDER = [
  'lifecycle', 'quality', 'engineering', 'data', 'design', 'docs', 'marketing', 'uncategorized',
]

function tierAnnotation(model) {
  const hint = MODEL_TIER_HINT[(model || '').trim()]
  return hint ? `_Suggested model tier: ${hint}_` : ''
}

function shortDescription(desc) {
  let d = (desc || '').split('. ')[0]
  if (d.length > 140) d = d.slice(0, 137) + '...'
  return d
}

// Mirror modules.py split_frontmatter: simple `key: value` block with indented
// continuation lines folded into the previous key.
function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return { fm: {}, body: text }
  const end = text.indexOf('\n---\n', 4)
  if (end === -1) return { fm: {}, body: text }
  const block = text.slice(4, end)
  const body = text.slice(end + 5)
  const fm = {}
  let currentKey = null
  for (const line of block.split('\n')) {
    if (!line.trim()) continue
    if (/^\s/.test(line) && currentKey) {
      fm[currentKey] = `${fm[currentKey]} ${line.trim()}`.trim()
      continue
    }
    const idx = line.indexOf(':')
    if (idx !== -1) {
      currentKey = line.slice(0, idx).trim()
      fm[currentKey] = line.slice(idx + 1).trim()
    }
  }
  return { fm, body }
}

function listModules(modulesDir) {
  const out = []
  let entries = []
  try {
    entries = fs.readdirSync(modulesDir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    const skillMd = path.join(modulesDir, entry.name, 'SKILL.md')
    if (!fs.existsSync(skillMd)) continue // skips shared-reference dirs like _lib/
    const { fm, body } = parseFrontmatter(fs.readFileSync(skillMd, 'utf8'))
    out.push({
      slug: entry.name,
      category: fm.category || 'uncategorized',
      tier: fm.tier || 'on-demand',
      slash: (fm.slash_command || '').replace(/^\//, ''),
      description: fm.description || '',
      model: fm.model || '',
      fm,
      body,
    })
  }
  out.sort((a, b) =>
    (a.tier !== 'core') - (b.tier !== 'core') ||
    a.category.localeCompare(b.category) ||
    a.slug.localeCompare(b.slug))
  return out
}

function renderCommandAlias(m) {
  const lines = ['---', `description: ${shortDescription(m.description)}`]
  if (m.model) lines.push(`model: ${m.model}`)
  const allowed = (m.fm['allowed-tools'] || '').trim()
  if (allowed) lines.push(`allowed-tools: ${allowed}`)
  if (m.body.includes('$ARGUMENTS') || m.body.includes('$1')) lines.push('argument-hint: [arguments]')
  lines.push('---', '', ALIAS_MARKER, '', `Use the \`${m.fm.name || m.slug}\` skill.`, '', '$ARGUMENTS', '')
  return lines.join('\n')
}

function readManifest(skillsDir) {
  try {
    return JSON.parse(fs.readFileSync(path.join(skillsDir, MANIFEST_NAME), 'utf8'))
  } catch {
    return {}
  }
}

// Emit all modules as Claude Code skills + slash aliases, then prune stale ones.
// Returns { skills, commands, prunedSkills, prunedCommands }.
function emitClaudeModules(modulesDir, skillsDir, commandsDir) {
  fs.mkdirSync(skillsDir, { recursive: true })
  fs.mkdirSync(commandsDir, { recursive: true })

  const prev = readManifest(skillsDir)
  const prevSkills = new Set(prev.skills || [])
  const prevCmds = new Set(prev.commands || [])

  const modules = listModules(modulesDir)
  const currentSkills = []
  const currentCmds = []

  for (const m of modules) {
    const target = path.join(skillsDir, m.slug)
    fs.rmSync(target, { recursive: true, force: true })
    fs.cpSync(path.join(modulesDir, m.slug), target, { recursive: true })
    fs.writeFileSync(path.join(target, GENERATED_MARKER),
      'Generated by 100xprism from modules/<slug>/SKILL.md. Regenerate instead of editing here.\n')
    currentSkills.push(m.slug)
    if (m.slash) {
      fs.writeFileSync(path.join(commandsDir, `${m.slash}.md`), renderCommandAlias(m))
      currentCmds.push(m.slash)
    }
  }

  const curSkillSet = new Set(currentSkills)
  const curCmdSet = new Set(currentCmds)

  // Prune skills we previously emitted / marked / shipped-as-removed that are gone now.
  const orphanSkills = new Set([...prevSkills, ...REMOVED_MODULES].filter(s => !curSkillSet.has(s)))
  for (const child of fs.readdirSync(skillsDir, { withFileTypes: true })) {
    if (child.isDirectory() && !curSkillSet.has(child.name) &&
        fs.existsSync(path.join(skillsDir, child.name, GENERATED_MARKER))) {
      orphanSkills.add(child.name)
    }
  }
  let prunedSkills = 0
  for (const slug of orphanSkills) {
    const p = path.join(skillsDir, slug)
    const ours = fs.existsSync(path.join(p, GENERATED_MARKER)) || prevSkills.has(slug) || REMOVED_MODULES.has(slug)
    if (fs.existsSync(p) && ours) { fs.rmSync(p, { recursive: true, force: true }); prunedSkills++ }
  }

  // Prune slash-command aliases we previously wrote (marker-guarded).
  let prunedCommands = 0
  for (const name of prevCmds) {
    if (curCmdSet.has(name)) continue
    const f = path.join(commandsDir, `${name}.md`)
    try {
      if (fs.existsSync(f) && fs.readFileSync(f, 'utf8').includes(ALIAS_MARKER)) {
        fs.unlinkSync(f); prunedCommands++
      }
    } catch { /* ignore */ }
  }

  fs.writeFileSync(path.join(skillsDir, MANIFEST_NAME),
    JSON.stringify({ skills: currentSkills.slice().sort(), commands: currentCmds.slice().sort() }, null, 2) + '\n')

  return { skills: currentSkills.length, commands: currentCmds.length, prunedSkills, prunedCommands }
}

const HEADER =
  '# 100x Dev — Modules\n' +
  '# Generated by 100xprism (https://github.com/rajitsaha/100xprism)\n' +
  '# Source of truth: modules/<slug>/SKILL.md. Edit there and regenerate.\n\n'

function categorySortKey(c) {
  const i = CATEGORY_ORDER.indexOf(c)
  return i === -1 ? CATEGORY_ORDER.length : i
}

function emitIndex(modules) {
  const byCat = {}
  for (const m of modules) (byCat[m.category] = byCat[m.category] || []).push(m)
  const lines = []
  for (const cat of Object.keys(byCat).sort((a, b) => categorySortKey(a) - categorySortKey(b))) {
    lines.push(`**${cat.charAt(0).toUpperCase() + cat.slice(1)}** (${byCat[cat].length}):`)
    for (const m of byCat[cat]) {
      const slash = m.slash ? ` \`/${m.slash}\`` : ''
      const tier = tierAnnotation(m.model)
      lines.push(`- \`${m.slug}\`${slash} — ${shortDescription(m.description)}${tier ? ' ' + tier : ''}`)
    }
    lines.push('')
  }
  return lines.join('\n').replace(/\s+$/, '') + '\n'
}

// Single-file combined config (port of modules.py render_concat): inline core
// module bodies + an index of on-demand modules. Used for .cursorrules/AGENTS.md/etc.
function generateCombinedConfig(modulesDir) {
  const modules = listModules(modulesDir)
  const core = modules.filter(m => m.tier === 'core')
  const onDemand = modules.filter(m => m.tier !== 'core')
  const out = [HEADER, '## Core modules (always-on)\n']
  core.sort((a, b) => categorySortKey(a.category) - categorySortKey(b.category) || a.slug.localeCompare(b.slug))
  for (const m of core) {
    out.push(`---\n\n## ${m.slug}\n`)
    if (m.slash) out.push(`_Slash command: \`/${m.slash}\`_\n`)
    const tier = tierAnnotation(m.model)
    if (tier) out.push(`${tier}\n`)
    out.push(m.body.replace(/^\n+/, '').replace(/\s+$/, '') + '\n\n')
  }
  out.push('---\n\n## On-demand modules (invoke by name)\n\n')
  out.push('These load only when triggered. Ask Claude to use the relevant module by name when the situation matches.\n\n')
  out.push(emitIndex(onDemand))
  return out.join('')
}

function renderCodexAgents(modules) {
  const out = [
    '# 100x Dev for Codex\n',
    '# Generated by 100xprism (https://github.com/rajitsaha/100xprism)\n',
    '# Source of truth: modules/<slug>/SKILL.md. Regenerate instead of hand-editing.\n\n',
    '## How Codex Should Use 100x Dev\n\n',
    '- Full reusable workflows live in `.agents/skills/<slug>/SKILL.md` so Codex can load them on demand.\n',
    '- When the user names a 100xprism slash workflow like `/gate`, treat it as a request to use the matching skill listed below.\n',
    '- Prefer explicit skill invocation (`$gate`, `$commit`, `$test`, etc.) or `/skills` when available; custom prompt slash commands are intentionally not generated.\n',
    '- Codex hooks, when generated, live in `.codex/hooks.json`. Review and trust them with `/hooks` before expecting enforcement.\n',
    '- Claude Code plugins in `plugins/plugins.json` are not Codex plugins. Use Codex `/plugins` for Codex-native plugins and app/MCP integrations.\n\n',
    '## 100xprism Command Map\n\n',
  ]

  for (const m of modules.filter(m => m.slash).sort((a, b) => a.slash.localeCompare(b.slash))) {
    out.push(`- \`/${m.slash}\` → \`$${m.slug}\` — ${shortDescription(m.description)}\n`)
  }

  out.push('\n## Available Skills\n\n')
  out.push('Codex can invoke these implicitly from their descriptions or explicitly by `$name` / `/skills`.\n\n')
  out.push(emitIndex(modules))
  return out.join('')
}

function codexHookCommand(script) {
  return `python3 .codex/100xprism-hooks/run-hook.py ${JSON.stringify(script).slice(1, -1)}`
}

function hookEnabled(hook) {
  const env = hook.toggle_env
  if (env && Object.prototype.hasOwnProperty.call(process.env, env)) {
    const val = String(process.env[env]).trim().toLowerCase()
    if (['1', 'true', 'yes', 'on'].includes(val)) return true
    if (['0', 'false', 'no', 'off', ''].includes(val)) return false
  }
  return Boolean(hook.default)
}

function codexHookWrapper(manifest) {
  const allowed = (manifest.hooks || [])
    .map(hook => hook && hook.script)
    .filter(Boolean)
    .sort()
  const template = fs.readFileSync(
    path.join(__dirname, '..', '..', 'adapters', 'templates', 'codex-run-hook.py'),
    'utf8',
  )
  return template.replace('__ALLOWED_HOOKS_JSON__', JSON.stringify(allowed))
}

function emitCodexProject(modulesDir, projectPath, hooksManifestPathOrDir) {
  const modules = listModules(modulesDir)
  const absProject = path.resolve(projectPath)

  fs.mkdirSync(absProject, { recursive: true })
  fs.writeFileSync(path.join(absProject, 'AGENTS.md'), renderCodexAgents(modules))

  const skillsDir = path.join(absProject, '.agents', 'skills')
  if (fs.existsSync(skillsDir)) {
    for (const child of fs.readdirSync(skillsDir, { withFileTypes: true })) {
      if (!child.isDirectory()) continue
      const target = path.join(skillsDir, child.name)
      if (fs.existsSync(path.join(target, GENERATED_MARKER))) {
        fs.rmSync(target, { recursive: true, force: true })
      }
    }
  }
  fs.mkdirSync(skillsDir, { recursive: true })

  let skillCount = 0
  for (const m of modules) {
    const source = path.join(modulesDir, m.slug)
    const target = path.join(skillsDir, m.slug)
    if (fs.existsSync(target)) {
      if (fs.existsSync(path.join(target, GENERATED_MARKER))) {
        fs.rmSync(target, { recursive: true, force: true })
      } else {
        console.error(`skipped existing non-100xprism skill: ${target}`)
        continue
      }
    }
    fs.cpSync(source, target, { recursive: true })
    fs.writeFileSync(
      path.join(target, GENERATED_MARKER),
      'Generated by 100xprism from modules/<slug>/SKILL.md. Regenerate instead of editing here.\n',
    )
    skillCount++
  }

  const manifestPath = fs.statSync(hooksManifestPathOrDir).isDirectory()
    ? path.join(hooksManifestPathOrDir, 'hooks.manifest.json')
    : hooksManifestPathOrDir
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  const codexDir = path.join(absProject, '.codex')
  const wrapperDir = path.join(codexDir, '100xprism-hooks')
  fs.mkdirSync(wrapperDir, { recursive: true })
  const wrapper = path.join(wrapperDir, 'run-hook.py')
  fs.writeFileSync(wrapper, codexHookWrapper(manifest))
  try { fs.chmodSync(wrapper, 0o755) } catch { /* ignore chmod on restricted filesystems */ }

  const hooks = {}
  for (const hook of manifest.hooks || []) {
    if (!hookEnabled(hook)) continue
    hooks[hook.event] = hooks[hook.event] || []
    hooks[hook.event].push({
      matcher: hook.matcher,
      hooks: [{
        type: 'command',
        command: codexHookCommand(hook.script),
        statusMessage: `100xprism: ${hook.description}`,
      }],
    })
  }
  fs.writeFileSync(path.join(codexDir, 'hooks.json'), JSON.stringify({ hooks }, null, 2) + '\n')

  return { skills: skillCount, hookGroups: Object.values(hooks).reduce((n, groups) => n + groups.length, 0) }
}

function scaffoldClaudeMd(projectPath) {
  const existing = [
    'CLAUDE.md', 'AGENTS.md', '.cursorrules', '.windsurfrules', 'GEMINI.md',
    path.join('.github', 'copilot-instructions.md'),
  ]
  if (existing.some(f => fs.existsSync(path.join(projectPath, f)))) return

  const projectName = path.basename(path.resolve(projectPath))
  fs.writeFileSync(path.join(projectPath, 'CLAUDE.md'), `# ${projectName} — Project Instructions

<!-- Generated by 100xprism. Fill in the sections below so modules like /db, /gate, /launch have project context. -->

## Project

<!-- Describe what this project does in 2-3 sentences. Used by /architect and /enterprise-design. -->
description: TODO

## Database

<!-- Used by /db and /query. Remove if not applicable. -->
# engine: postgres
# connection: default
# connections:
#   default:
#     host: localhost
#     port: 5432
#     name: mydb
#     user: myuser
#     auth: env:DB_PASSWORD

## Cloud (GCP)

<!-- Used by /gate, /cloud-security, /launch. Remove if not on GCP. -->
# gcp_project: my-gcp-project
# cloud_run_service: my-service
# region: us-central1

## Production

<!-- Used by /launch and /push for health checks and smoke tests. -->
# production_url: https://example.com
# health_url: https://example.com/health

## Security Exceptions

# security_exceptions:
#   - CVE-2023-XXXX: false positive in test dependency

## Rules

<!-- Add project-specific rules for Claude here. /update-claude appends to this section. -->
`)
  console.log(`  → Scaffolded CLAUDE.md in ${projectPath} ✓`)
}

// Reconcile enabledPlugins with plugins.json: ADD newly-declared plugins and
// REMOVE ones 100xprism previously installed but has since dropped — without
// touching plugins the user enabled themselves. The "managed" set is tracked in
// a sidecar beside settings.json (mirrors adapters/lib/sync_plugins.py). On the
// first run (no state) the managed set is seeded from declared ∧ enabled, so
// nothing is removed until a later run observes an actual drop.
function mergePluginsJson(pluginsFile, settingsFile) {
  if (!fs.existsSync(settingsFile)) {
    fs.mkdirSync(path.dirname(settingsFile), { recursive: true })
    fs.writeFileSync(settingsFile, '{}')
  }
  const pluginsData = JSON.parse(fs.readFileSync(pluginsFile, 'utf8'))
  const settings = JSON.parse(fs.readFileSync(settingsFile, 'utf8'))
  const enabled = settings.enabledPlugins || {}
  const desired = pluginsData.plugins || []
  const desiredSet = new Set(desired)

  const stateFile = path.join(path.dirname(settingsFile), '.100xprism-plugins.json')
  let state = {}
  try { state = JSON.parse(fs.readFileSync(stateFile, 'utf8')) } catch { state = {} }
  const firstRun = !('managed' in state)
  const managed = new Set(
    firstRun ? desired.filter(p => p in enabled) : (state.managed || []),
  )

  for (const p of desired) {
    if (!(p in enabled)) enabled[p] = true   // never flip an existing value
  }
  for (const p of managed) {
    if (!desiredSet.has(p)) delete enabled[p] // we installed it; it's gone now
  }

  settings.enabledPlugins = enabled
  settings.extraKnownMarketplaces = {
    ...settings.extraKnownMarketplaces,
    ...(pluginsData.extraKnownMarketplaces || {}),
  }
  fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2))
  fs.writeFileSync(stateFile, JSON.stringify({ managed: [...desiredSet].sort() }, null, 2))
}

function addTrackedProject(projectPath, trackedFile) {
  fs.mkdirSync(path.dirname(trackedFile), { recursive: true })
  const existing = fs.existsSync(trackedFile)
    ? fs.readFileSync(trackedFile, 'utf8').split('\n').filter(Boolean)
    : []
  if (!existing.includes(projectPath)) {
    fs.appendFileSync(trackedFile, projectPath + '\n')
  }
}

function writeAdapter(content, outputFile) {
  fs.mkdirSync(path.dirname(outputFile), { recursive: true })
  fs.writeFileSync(outputFile, content)
  console.log(`  → Generated ${outputFile} ✓`)
}

function installGlobalWindows(installDir) {
  const { claudeDir, claudeCommandsDir, claudeSettingsFile } = require('../platform')
  const skillsDir = path.join(claudeDir, 'skills')
  const r = emitClaudeModules(path.join(installDir, 'modules'), skillsDir, claudeCommandsDir)
  mergePluginsJson(path.join(installDir, 'plugins', 'plugins.json'), claudeSettingsFile)
  const pruned = (r.prunedSkills || r.prunedCommands)
    ? ` (pruned ${r.prunedSkills} stale skill(s), ${r.prunedCommands} stale alias(es))`
    : ''
  console.log(`✓ ${r.skills} skills + ${r.commands} slash aliases installed to ~/.claude/${pruned}`)
  console.log('✓ Plugins merged into ~/.claude/settings.json')
  console.log('\nNext: cd into a project and run  100xprism init  to set it up.')
}

function initProjectWindows(installDir, projectPath) {
  const { trackedProjectsFile } = require('../platform')
  const modulesDir = path.join(installDir, 'modules')
  const absProject = path.resolve(projectPath)
  const readline = require('readline')
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

  console.log('\n100x Dev — Project Setup')
  console.log(`  Project: ${absProject}\n`)

  const tools = [
    { label: 'Claude Code (CLAUDE.md scaffold)', key: 'claude' },
    { label: 'Cursor (.cursorrules)', key: 'cursor' },
    { label: 'Codex (AGENTS.md)', key: 'codex' },
    { label: 'Windsurf (.windsurfrules)', key: 'windsurf' },
    { label: 'Copilot CLI (.github/copilot-instructions.md)', key: 'copilot' },
    { label: 'Gemini CLI (GEMINI.md)', key: 'gemini' },
    { label: 'Antigravity (ANTIGRAVITY.md)', key: 'antigravity' },
  ]
  const selected = {}

  function promptNext(idx) {
    if (idx >= tools.length) {
      rl.close()
      applyAdapters()
      return
    }
    rl.question(`  Set up ${tools[idx].label}? [y/N] `, ans => {
      selected[tools[idx].key] = /^y$/i.test(ans.trim())
      promptNext(idx + 1)
    })
  }

  function applyAdapters() {
    const combined = generateCombinedConfig(modulesDir)
    if (selected.claude)      scaffoldClaudeMd(absProject)
    if (selected.cursor)      writeAdapter(combined, path.join(absProject, '.cursorrules'))
    if (selected.codex) {
      const r = emitCodexProject(modulesDir, absProject, path.join(installDir, 'hooks'))
      console.log(`  → Generated Codex AGENTS.md + ${r.skills} repo skills + hooks ✓`)
    }
    if (selected.windsurf)    writeAdapter(combined, path.join(absProject, '.windsurfrules'))
    if (selected.copilot)     writeAdapter(combined, path.join(absProject, '.github', 'copilot-instructions.md'))
    if (selected.gemini)      writeAdapter(combined, path.join(absProject, 'GEMINI.md'))
    if (selected.antigravity) writeAdapter(combined, path.join(absProject, 'ANTIGRAVITY.md'))
    addTrackedProject(absProject, trackedProjectsFile)
    console.log('\n✓ Project set up!')
  }

  promptNext(0)
}

function updateWindows(installDir, checkOnly) {
  const fetchResult = spawnSync('git', ['-C', installDir, 'fetch', 'origin', 'main', '--quiet'], { stdio: 'inherit' })
  if (fetchResult.status !== 0) { console.error('git fetch failed'); process.exit(1) }

  const local  = spawnSync('git', ['-C', installDir, 'rev-parse', 'HEAD']).stdout.toString().trim()
  const remote = spawnSync('git', ['-C', installDir, 'rev-parse', 'origin/main']).stdout.toString().trim()

  if (local === remote) { console.log('✓ Already up to date.'); return }

  if (checkOnly) { console.log('Update available. Run: 100xprism update'); return }

  const pullResult = spawnSync('git', ['-C', installDir, 'pull', '--rebase', 'origin', 'main', '--quiet'], { stdio: 'inherit' })
  if (pullResult.status !== 0) { console.error('git pull failed'); process.exit(1) }

  installGlobalWindows(installDir)
  console.log('✓ 100xprism updated!')
}

module.exports = {
  parseFrontmatter,
  shortDescription,
  listModules,
  renderCommandAlias,
  emitClaudeModules,
  generateCombinedConfig,
  renderCodexAgents,
  emitCodexProject,
  scaffoldClaudeMd,
  mergePluginsJson,
  addTrackedProject,
  installGlobalWindows,
  initProjectWindows,
  updateWindows,
}
